config/routes.rb
Rails.application.routes.draw do
  get 'starships/show', as: :show_starship
  get 'starships/index', as: :index_starships
  get 'planets/show', as: :show_planet
  get 'planets/index', as: :index_planets
  get 'people/show', as: :show_person
  get 'people/index', as: :index_people
  get 'films/show', as: :show_film
  get 'films/index', as: :index_films
  root 'films#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def show
    url = params[:url]
    response = RestClient.get url
    f = JSON.parse(response.body)
    @film = Hash.new
    @film["title"] = f["title"]
    @film["episode_id"] = f["episode_id"]
    @film["opening_crawl"] = f["opening_crawl"]
    @film["director"] = f["director"]
    @film["producer"] = f["producer"]
    @film["release_date"] = f["release_date"]
    @film["created_at_swapi"] = f["created"]
    @film["edited_at_swapi"] = f["edited"]
    @film["url"] = f["url"]
    @film["characters"] = []
    @film["planets"] = []
    @film["starships"] = []
    people_in_film = f["characters"]
    planets_in_film = f["planets"]
    starships_in_film = f["starships"]
    people_in_film.each do |p|
      person = OpenStruct.new
      response = RestClient.get p
      r = JSON.parse(response.body)
      person.name = r["name"]
      person.url = p
      @film["characters"] << person
    end
    planets_in_film.each do |p|
      planet = OpenStruct.new
      response = RestClient.get p
      r = JSON.parse(response.body)
      planet.name = r["name"]
      planet.url = p
      @film["planets"] << planet
    end
    starships_in_film.each do |s|
      starship = OpenStruct.new
      response = RestClient.get s
      r = JSON.parse(response.body)
      starship.name = r["name"]
      starship.url = s
      @film["starships"] << starship
    end
    @film
  end

  def index
    last_page = false
    response = RestClient.get 'https://swapi.co/api/films/'
    response_parsed = JSON.parse(response.body)
    @films = []
    while !last_page
      response_parsed["results"].each do |f|
        new_params = Hash.new
        new_params["title"] = f["title"]
        new_params["episode_id"] = f["episode_id"]
        new_params["opening_crawl"] = f["opening_crawl"]
        new_params["director"] = f["director"]
        new_params["producer"] = f["producer"]
        new_params["release_date"] = f["release_date"]
        new_params["created_at_swapi"] = f["created"]
        new_params["edited_at_swapi"] = f["edited"]
        new_params["url"] = f["url"]
        @films << new_params
      end
      next_url = response_parsed["next"]
      if next_url
        response = RestClient.get(next_url)
        response_parsed = JSON.parse(response.body)
      else
        last_page = true
      end
    end
    @films
  end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Films</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Episode</th>
      <!-- <th>Opening crawl</th> -->
      <th>Director</th>
      <th>Producer</th>
      <th>Release date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= film["title"] %></td>
        <td><%= film["episode_id"] %></td>
        <!-- <td><%= film["opening_crawl"] %></td> -->
        <td><%= film["director"] %></td>
        <td><%= film["producer"] %></td>
        <td><%= film["release_date"] %></td>
        <td><%= link_to 'Show', show_film_path(url: film["url"]) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Films', index_films_path %> |
<%= link_to 'People', index_people_path %> |
<%= link_to 'Planets', index_planets_path %> |
<%= link_to 'Starships', index_starships_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @film["title"] %>
</p>

<p>
  <strong>Episode:</strong>
  <%= @film["episode_id"] %>
</p>

<p>
  <strong>Opening crawl:</strong>
  <%= @film["opening_crawl"] %>
</p>

<p>
  <strong>Director:</strong>
  <%= @film["director"] %>
</p>

<p>
  <strong>Producer:</strong>
  <%= @film["producer"] %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @film["release_date"] %>
</p>

<p>
  <strong>Created at swapi:</strong>
  <%= @film["created_at_swapi"] %>
</p>

<p>
  <strong>Edited at swapi:</strong>
  <%= @film["edited_at_swapi"] %>
</p>

<p>
  <strong>Url:</strong>
  <%= @film["url"] %>
</p>

<p>
  <strong>Characters:</strong>
  <% @film["characters"].each do |p| %>
  <tr>
    <td><%= link_to p.name, show_person_path(url: p.url) %></td>
  </tr>
  <% end %>
</p>
<p>
  <strong>Planets:</strong>
  <% @film["planets"].each do |p| %>
  <tr>
    <td><%= link_to p.name, show_planet_path(url: p.url) %></td>

  </tr>
  <% end %>
</p>

<p>
  <strong>Starships:</strong>
  <% @film["starships"].each do |s| %>
  <tr>
    <td><%= link_to s.name, show_starship_path(url: s.url) %></td>

  </tr>
  <% end %>
</p>

<%= link_to 'Films', index_films_path %> |
<%= link_to 'People', index_people_path %> |
<%= link_to 'Planets', index_planets_path %> |
<%= link_to 'Starships', index_starships_path %>